import type { Field, ModuleConfig } from "./ui-config";
import { rfqStatuses } from "./commercial";
const f = (
  key: string,
  label: string,
  type: Field["type"] = "text",
  required = false,
  options?: readonly string[],
  source?: string,
): Field => ({ key, label, type, required, options, source });
const r = (key: string, label: string, source: string, required = false) =>
  f(key, label, "relation", required, undefined, source);
const n = f("notes", "Notes", "textarea");
export const historicalFields = [
  f("historical", "Historical record", "boolean"),
  f("originalDate", "Original transaction date", "date"),
  {
    ...f("recordSource", "Record source", "select", true, [
      "MANUAL",
      "PDF_ASSISTED",
      "SYSTEM_GENERATED",
      "FUTURE_IMPORT",
      "FUTURE_ACCOUNTING_SYNC",
    ]),
    default: "MANUAL",
  },
];
const amount = (key: string, label: string) => ({
  ...f(key, label, "number", true),
  default: "0",
});
export const commercialConfigs: Record<string, ModuleConfig> = {
  decisions: {
    title: "Tender decisions",
    description:
      "Human Go / No-Go decisions with immutable history. Reject requires confirmation.",
    columns: ["tender", "decision", "reason", "decisionAt"],
    immutable: true,
    fields: [
      r("tenderId", "Tender", "tenders", true),
      f("decision", "Commercial decision", "select", true, [
        "PENDING_REVIEW",
        "PURSUE",
        "REJECT",
        "REVIEW_LATER",
      ]),
      f("reason", "Decision reason", "select", false, [
        "PRODUCT_UNSUITABLE",
        "PRICE_UNCOMPETITIVE",
        "MANUFACTURER_UNAVAILABLE",
        "AUTHORIZATION_UNAVAILABLE",
        "DELIVERY_UNSUITABLE",
        "LOW_VIABILITY",
        "COMPETITOR_ADVANTAGE",
        "INSUFFICIENT_TIME",
        "STRATEGIC_REJECTION",
        "OTHER",
      ]),
      n,
      f("confirmed", "I confirm this rejection", "boolean"),
    ],
  },
  "manufacturer-contacts": {
    title: "Manufacturer contacts",
    description:
      "Multiple contacts, regions and preferred communication channels.",
    columns: ["name", "manufacturer", "department", "email", "active"],
    fields: [
      r("manufacturerId", "Manufacturer", "manufacturers", true),
      f("name", "Contact name", "text", true),
      f("designation", "Designation"),
      f("department", "Department"),
      f("email", "Email", "email"),
      f("phone", "Phone"),
      f("whatsapp", "WhatsApp number"),
      f("region", "Region"),
      f("category", "Product category"),
      {
        ...f("preferredChannel", "Preferred channel", "select", true, [
          "EMAIL",
          "PHONE",
          "WHATSAPP",
          "OTHER",
        ]),
        default: "EMAIL",
      },
      { ...f("active", "Active contact", "boolean"), default: true },
      n,
    ],
  },
  rfqs: {
    title: "RFQs",
    createLabel: "New RFQ",
    description:
      "Create directly or prefill from a tender/customer. Sending and follow-ups are recorded explicitly.",
    files: true,
    columns: [
      "number",
      "manufacturer",
      "productName",
      "status",
      "quoteRequiredBy",
      "assignee",
    ],
    fields: [
      f("number", "RFQ number", "text", true),
      r("tenderId", "Tender (optional)", "tenders"),
      r("customerId", "Customer (optional)", "customers"),
      r("manufacturerId", "Manufacturer", "manufacturers", true),
      r("contactId", "Manufacturer contact", "manufacturer-contacts"),
      r("productId", "Saved product", "products"),
      f("productName", "Equipment/product", "text", true),
      f("model", "Model"),
      { ...f("quantity", "Quantity", "number", true), default: 1 },
      f("accessories", "Accessories", "textarea"),
      f("warrantyRequirement", "Warranty requirement", "textarea"),
      f("deliveryLocation", "Delivery location"),
      f("requiredDeliveryTime", "Required delivery time"),
      f("tenderDeadline", "Tender deadline", "datetime-local"),
      f("quoteRequiredBy", "Quote required by", "datetime-local"),
      r("assignedToId", "Assigned employee", "employees"),
      {
        ...f("status", "RFQ status", "select", true, rfqStatuses),
        default: "DRAFT",
      },
      f("sentAt", "Actual sent date", "datetime-local"),
      n,
      ...historicalFields,
    ],
  },
  "rfq-followups": {
    title: "RFQ follow-ups",
    description: "Record quotation follow-up and the next action date.",
    columns: ["rfq", "contactDate", "nextDate", "notes"],
    fields: [
      r("rfqId", "RFQ", "rfqs", true),
      r("employeeId", "Employee", "employees"),
      f("contactDate", "Contact date", "datetime-local", true),
      f("nextDate", "Next follow-up", "datetime-local"),
      f("notes", "Follow-up notes", "textarea", true),
    ],
  },
  quotes: {
    title: "Manufacturer quotations",
    createLabel: "Add Manufacturer Quote",
    description:
      "Manual quotations with immutable revisions. Amounts come from the actual manufacturer quote.",
    files: true,
    immutable: true,
    columns: [
      "number",
      "revision",
      "manufacturer",
      "productName",
      "currency",
      "total",
      "validityDate",
      "isFinal",
    ],
    fields: [
      r("previousQuoteId", "Previous revision (optional)", "quotes"),
      f("number", "Quotation number", "text", true),
      r("manufacturerId", "Manufacturer", "manufacturers", true),
      r("rfqId", "RFQ (optional)", "rfqs"),
      r("tenderId", "Tender (optional)", "tenders"),
      r("productId", "Saved product", "products"),
      f("quotationDate", "Quotation date", "date", true),
      f("validityDate", "Valid until", "date"),
      { ...f("currency", "Currency code", "text", true), default: "INR" },
      f("productName", "Equipment/product", "text", true),
      f("model", "Model"),
      { ...f("quantity", "Quantity", "number", true), default: 1 },
      f("unitPrice", "Unit price", "number", true),
      amount("taxAmount", "Tax amount"),
      f("accessories", "Accessories", "textarea"),
      amount("accessoriesCost", "Accessories cost"),
      amount("freight", "Freight"),
      amount("installation", "Installation cost"),
      f("warranty", "Warranty terms", "textarea"),
      amount("warrantyCost", "Warranty cost"),
      amount("extendedWarrantyCost", "Extended warranty cost"),
      amount("otherCosts", "Other costs"),
      amount("discount", "Discount amount"),
      f(
        "finalManufacturerPrice",
        "Actual quoted final price (optional override)",
        "number",
      ),
      f("leadTimeDays", "Delivery lead time (days)", "number"),
      f("paymentTerms", "Payment terms", "textarea"),
      f("isFinal", "Final quotation", "boolean"),
      n,
      ...historicalFields,
    ],
  },
  comparisons: {
    title: "Commercial assumptions",
    createLabel: "New Comparison",
    description:
      "Compare entered costs and selling assumptions. Human selection remains final; no winner is recommended.",
    columns: [
      "name",
      "quote",
      "currency",
      "totalCost",
      "sellingPrice",
      "contribution",
      "marginPercent",
    ],
    fields: [
      f("name", "Comparison/option name", "text", true),
      r("tenderId", "Tender (optional)", "tenders"),
      r("rfqId", "RFQ (optional)", "rfqs"),
      r("quoteId", "Quotation revision (optional)", "quotes"),
      { ...f("currency", "Currency code", "text", true), default: "INR" },
      f(
        "procurementCost",
        "Procurement cost (leave blank to use quote)",
        "number",
      ),
      amount("additionalCosts", "Additional commercial costs"),
      f("sellingPrice", "Proposed selling price (total)", "number", true),
      f("leadTimeDays", "Delivery lead time (days)", "number"),
      n,
    ],
  },
  results: {
    title: "Tender win/loss results",
    description:
      "Record actual outcomes and known competitor information. Results remain in history.",
    immutable: true,
    columns: ["tender", "outcome", "resultDate", "winner", "reason"],
    fields: [
      r("tenderId", "Tender", "tenders", true),
      f("outcome", "Outcome", "select", true, [
        "WON",
        "LOST",
        "CANCELLED",
        "NO_BID",
      ]),
      f("resultDate", "Result date", "date", true),
      f("winner", "Known winner"),
      f("winningPrice", "Known winning price (optional)", "number"),
      f("competitorName", "Competitor name"),
      f("reason", "Result reason", "select", false, [
        "PRICE",
        "TECHNICAL",
        "DOCUMENTATION",
        "AUTHORIZATION",
        "DELIVERY",
        "ELIGIBILITY",
        "COMMERCIAL_DECISION",
        "BID_NOT_SUBMITTED",
        "UNKNOWN",
        "OTHER",
      ]),
      n,
      ...historicalFields,
    ],
  },
};
